[package]
edition = "2021"
name = "fhl-client"
version = "2.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# DTOs and common modeling for the wrangler
wrangler-common = {path = "../common"}

yew = {version = "0.21", features = ["csr"]}

js-sys = "0.3.74"

wasm-bindgen = "0.2.97"
wasm-bindgen-futures = "0.4.47"

web-sys = "0.3.74"

tracing = "0.1.41"
tracing-core = "0.1.33"
tracing-subscriber = {version = "0.3.19", features = ["fmt", "time"]}
tracing-web = "0.1.3"

# Serializing conmmunications
serde = {version = "1.0.215", features = ["derive"]}
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.133"

uuid = "1.11.0"
